import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default:"آرمان آروین پارتاک",
    template:"%s | آرمان آروین پارتاک",
    absolute:"",
  },
  icons: {
    icon: '/fav.png',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  );
}
